feat: handle commands error

diff --git a/discup b/discup
--- a/discup
+++ b/discup
@@ -33,17 +33,46 @@ fi
 if [[ -d $DISCORD_FOLDER_PATH ]]; then
     echo "[*] Removing previous Discord version."
     sudo rm -fr $DISCORD_FOLDER_PATH
+
+    if [[ ! $? -eq 0 ]]; then
+        echo "[-] Failed to remove previous Discord version folder."
+        exit $?
+    fi
+
     echo "[+] Removed current Discord version folder."
+fi
+
+if [[ -f $DISCORD_DESKTOP_CONFIG_FILE_PATH ]]; then
+    echo "[*] Removing previous Discord desktop config file."
+    sudo rm -fr $DISCORD_FOLDER_PATH
+
+    if [[ ! $? -eq 0 ]]; then
+        echo "[-] Failed to remove previous Discord config file."
+        exit $?
+    fi
+
+    echo "[+] Removed previous Discord desktop config file."
+fi
+
+if [[ -f $DISCORD_BINARY_LINK_FILE_PATH ]]; then
+    echo "[*] Unlinking previous version."
+    sudo unlink $DISCORD_BINARY_LINK_FILE_PATH
+
+    if [[ ! $? -eq 0 ]]; then
+        echo "[-] Failed to unlink previous Discord binary file."
+        exit $?
+    fi
+
+    echo "[+] Unlinked file."
 fi
 
 echo "[*] Extracting Discord to $DISCORD_PARENT_PATH"
 sudo tar -xvzf $UPDATE_VERSION_COMPRESSED_FILE_PATH -C $THIRD_PARTY_PROGRAMS
 echo "[+] Discord extracted to $DISCORD_PARENT_PATH"
 
-if [[ ! -f $DISCORD_DESKTOP_CONFIG_FILE_PATH ]]; then
-    echo "[*] Creating Discord desktop config file."
+echo "[*] Creating Discord desktop config file."
 
-    cat > $DISCORD_DESKTOP_CONFIG_FILE_PATH <<EOF
+cat > $DISCORD_DESKTOP_CONFIG_FILE_PATH <<EOF
 [Desktop Entry]
 Name=Discord
 StartupWMClass=discord
@@ -55,14 +84,8 @@ Type=Application
 Categories=Network;InstantMessaging;
 Path=$BINARIES_PATH
 EOF
-    echo "[+] Created Discord desktop config file."
-fi
 
-if [[ -f $DISCORD_BINARY_LINK_FILE_PATH ]]; then
-    echo "[*] Unlinking previous version."
-    sudo unlink $DISCORD_BINARY_LINK_FILE_PATH
-    echo "[+] Unlinked file."
-fi
+echo "[+] Created Discord desktop config file."
 
 echo "[*] Linking new binary file version."
 sudo ln -s $DISCORD_BINARY_FILE_PATH $DISCORD_BINARY_LINK_FILE_PATH
