refactor: use `dpkg` to install discord

diff --git a/discup b/discup
--- a/discup
+++ b/discup
@@ -3,12 +3,8 @@
 # Enviroment
 APP_NAME="discup"
 APP_DESCRIPTION="A dump script to update the discord in linux."
-APP_VERSION="0.2.0"
+APP_VERSION="0.3.0"
 APP_OWNER="SadS4ndWiCh"
-
-# Exit codes
-ERR_MUST_BE_ROOT=1
-ERR_COMPRESSED_FILE_NOT_FOUND=2
 
 # Colors
 CL_RESET="\033[0m"
@@ -16,44 +12,19 @@ CL_ERROR="\033[0;31m"
 CL_SUCCESS="\033[0;32m"
 CL_INFO="\033[1;33m"
 
-# Essentials Paths
-BINARIES_PATH=/usr/local/bin
-APPLICATIONS_PATH=/usr/share/applications
-CONFIG_FOLDER=~/.config/$APP_NAME
-DESTINATION_DIRECTORY_LAST=$CONFIG_FOLDER/.discup_last
-
-# Arguments
-# discup [DESTINATION_DIRECTORY]
-DESTINATION_DIRECTORY=$1
-
 # Discord
-DISCORD_URL_DOWNLOAD="https://discord.com/api/download?platform=linux&format=tar.gz"
-DISCORD_DOWNLOAD_OUTPUT=/tmp/discord.tar.gz
-DISCORD_FOLDER_NAME="Discord"
-DISCORD_CONFIG_DESKTOP_NAME="discord.desktop"
-DISCORD_BINARY_NAME="discord.desktop"
-DISCORD_DEFAULT_DESTINATION=/opt/Discord
+DISCORD_URL_DOWNLOAD="https://discord.com/api/download?platform=linux"
+DISCORD_DOWNLOAD_OUTPUT=/tmp/discord.deb
 
 # Utils functions
 log_success() {
-    echo -e "[$CL_SUCCESS+$CL_RESET] $1"
+    echo -e "[$CL_SUCCESS+$CL_RESET] OK: $1"
 }
 log_error() {
-    echo -e "[$CL_ERROR-$CL_RESET] $1"
+    echo -e "[$CL_ERROR-$CL_RESET] ERROR: $1"
 }
 log_info() {
-    echo -e "[$CL_INFO*$CL_RESET] $1"
-}
-
-prompt() {
-    echo -n -e "[$CL_INFO*$CL_RESET] $1 [y/N] "
-    read -n 1 -r
-    echo
-    if [[ $REPLY =~ ^[Yy]$ ]]; then
-        return 1
-    fi
-
-    return 0
+    echo -e "[$CL_INFO*$CL_RESET] INFO: $1"
 }
 
 cat <<'END_HEADER'
@@ -74,230 +45,41 @@ cat <<'END_HEADER'
                                                                       "         
 END_HEADER
 
+echo $APP_DESCRIPTION
 echo "Developed by $APP_OWNER ~ Version $APP_VERSION"
 echo ""
 
-# Setup the config folder
-if [[ ! -d $CONFIG_FOLDER ]]; then
-    log_info "The discup config folder was not found."
-    log_info "Creating a new one at: $CONFIG_FOLDER"
+log_info "Downloading latest discord version..."
 
-    mkdir -p $CONFIG_FOLDER 2> /dev/null
-    if [[ ! $? -eq 0 ]]; then
-        log_error "Failed to create the config folder."
-        log_error "Create it manually with the following command:"
-        log_error "mkdir $CONFIG_FOLDER"
-    else
-        log_success "Successfuly created the config folder."
-    fi
+curl -s -f -L $DISCORD_URL_DOWNLOAD -o $DISCORD_DOWNLOAD_OUTPUT &> /dev/null
+if [[ ! $? -eq 0 ]]; then
+    log_error "Failed to download discord"
+    log_error "Maybe the discord server went down or the download link changes"
+    log_error "Used URL: $DISCORD_URL_DOWNLOAD"
+    exit $?
 fi
 
-# Checking the last directory register
-if [[ -d $CONFIG_FOLDER ]]; then
-    if [[ -f $DESTINATION_DIRECTORY_LAST ]]; then
-        OLD_DESTINATION_DIRECTORY_LAST=`cat $DESTINATION_DIRECTORY_LAST`
+log_success "Discord was downloaded successfuly"
+log_info "Installing discord..."
 
-        if [ -z $DESTINATION_DIRECTORY ]; then
-            log_info "The destination directory was not specified."
-            DESTINATION_DIRECTORY=$OLD_DESTINATION_DIRECTORY_LAST
-            log_success "Using the last directory: $OLD_DESTINATION_DIRECTORY_LAST"
+sudo -p "[*] ROOT: Type the user password: " dpkg -i $DISCORD_DOWNLOAD_OUTPUT &> /dev/null
+if [[ ! $? -eq 0 ]]; then
+    log_error "Failed to install discord"
+    log_error "Run the following command by yourself: dpkg -i $DISCORD_DOWNLOAD_OUTPUT"
+    exit $?
+fi
 
-        elif [ $DESTINATION_DIRECTORY != $OLD_DESTINATION_DIRECTORY_LAST ]; then
-            log_info "The new directory is different from the last one."
-            prompt "The last directory can be removed? $OLD_DESTINATION_DIRECTORY_LAST"
+log_success "Discord was installed successfuly"
 
-            if [[ $? -eq 1 ]]; then
-                log_info "Removing the last directory..."
+log_info "Removing discord installer"
 
-                if [ ! -w $OLD_DESTINATION_DIRECTORY_LAST ]; then
-                    sudo rm -r $OLD_DESTINATION_DIRECTORY_LAST 2> /dev/null
-                    if [[ $? -ne 0 ]]; then
-                        log_error "Failed to remove the last directory."
-                        log_error "Remove manually with the following command:"
-                        log_error "sudo rm -r $OLD_DESTINATION_DIRECTORY_LAST"
-                    fi
-                else
-                    rm -r $OLD_DESTINATION_DIRECTORY_LAST 2> /dev/null
-                    if [[ $? -ne 0 ]]; then
-                        log_error "Failed to remove the last directory."
-                        log_error "Remove manually with the following command:"
-                        log_error "rm -r $OLD_DESTINATION_DIRECTORY_LAST"
-                    fi
-                fi
+rm $DISCORD_DOWNLOAD_OUTPUT
 
-                
-                log_success "Successfuly removed the last destination."
-            else
-                log_error "You reject to delete last directory."
-            fi
-
-            echo $DESTINATION_DIRECTORY > $DESTINATION_DIRECTORY_LAST
-        fi
-    else
-        if [ -z $DESTINATION_DIRECTORY ]; then
-            DESTINATION_DIRECTORY=$DISCORD_DEFAULT_DESTINATION
-        fi
-
-        log_info "The register of the last directory was not found."
-        log_info "Creating a new one..."
-
-        echo $DESTINATION_DIRECTORY > $DESTINATION_DIRECTORY_LAST 2> /dev/null
-        if [[ ! $? -eq 0 ]]; then
-            log_error "Failed to create the register."
-            log_error "Create it manually with the following command:"
-            log_error "echo $DESTINATION_DIRECTORY > $DESTINATION_DIRECTORY_LAST"
-        else
-            log_success "Successfuly created the register at: $DESTINATION_DIRECTORY_LAST."
-        fi
-    fi
+if [[ ! $? -eq 0 ]]; then
+    log_error "Failed to remove discord installer"
+    log_error "Run the following command by yourself: rm -fr $DISCORD_DOWNLOAD_OUTPUT"
 else
-    if [ -z $DESTINATION_DIRECTORY ]; then
-        DESTINATION_DIRECTORY=$DISCORD_DEFAULT_DESTINATION
-    fi
+    log_success "Temp discord installer was successfuly removed"
 fi
 
-# Remove old version files
-if [[ -d $DESTINATION_DIRECTORY ]]; then
-    log_info "Removing previous Discord version..."
-
-    if [ ! -w $DESTINATION_DIRECTORY ]; then
-        sudo rm -r $DESTINATION_DIRECTORY 2> /dev/null
-        if [[ ! $? -eq 0 ]]; then
-          log_error "Failed to remove previous Discord version."
-          log_error "Remove manually with the following command:"
-          log_error "sudo rm -r $DESTINATION_DIRECTORY"
-          exit $?
-        fi
-    else
-        rm -r $DESTINATION_DIRECTORY 2> /dev/null
-        if [[ ! $? -eq 0 ]]; then
-          log_error "Failed to remove previous Discord version."
-          log_error "Remove manually with the following command:"
-          log_error "rm -r $DESTINATION_DIRECTORY"
-          exit $?
-        fi
-    fi
-
-    log_success "Successfuly removed previous Discord version."
-fi
-
-DISCORD_DESKTOP_CONFIG_FILE_PATH=$APPLICATIONS_PATH/discord.desktop
-if [[ -f $DISCORD_DESKTOP_CONFIG_FILE_PATH ]]; then
-    log_info "Removing previous Discord desktop config file..."
-    sudo rm -r $DISCORD_DESKTOP_CONFIG_FILE_PATH 2> /dev/null
-
-    if [[ ! $? -eq 0 ]]; then
-        log_error "Failed to remove previous Discord config file."
-        log_error "Remove manually with the following command:"
-        log_error "sudo rm -r $DISCORD_DESKTOP_CONFIG_FILE_PATH"
-        exit $?
-    fi
-
-    log_success "Successfuly removed previous Discord desktop config file."
-fi
-
-DISCORD_BINARY_LINK_FILE_PATH=$BINARIES_PATH/discord
-if [[ -L $DISCORD_BINARY_LINK_FILE_PATH ]]; then
-    log_info "Unlinking previous Discord version..."
-    sudo unlink $DISCORD_BINARY_LINK_FILE_PATH 2> /dev/null
-
-    if [[ ! $? -eq 0 ]]; then
-        log_error "Failed to unlink previous Discord version."
-        log_error "Remove manually with the following command:"
-        log_error "sudo rm -r $DISCORD_BINARY_LINK_FILE_PATH"
-        exit $?
-    fi
-
-    log_success "Successfuly unlinked previous Discord version."
-fi
-
-# Download Discord
-log_info "Downloading lastest Discord version..."
-wget "$DISCORD_URL_DOWNLOAD" -O "$DISCORD_DOWNLOAD_OUTPUT" -q 2> /dev/null
-if [[ ! $? -eq 0 ]]; then
-    log_error "Failed to download the new Discord version."
-    exit $?
-fi
-log_success "Successfuly downloaded latest Discord version."
-
-if [[ ! -f $DISCORD_DOWNLOAD_OUTPUT ]]; then
-    log_error "Compressed file not found."
-    exit $ERR_COMPRESSED_FILE_NOT_FOUND
-fi
-
-log_info "Extracting latest Discord version..."
-tar -xvzf $DISCORD_DOWNLOAD_OUTPUT -C /tmp > /dev/null 2> /dev/null
-if [[ ! $? -eq 0 ]]; then
-    log_error "Failed to extract compressed discord file."
-    exit $?
-fi
-log_success "Successfuly extracted Discord."
-
-# Create the Destination Directory folder
-PARENT_DESTINATION_DIRECTORY=$(dirname $DESTINATION_DIRECTORY)
-if [[ ! -d $DESTINATION_DIRECTORY ]]; then
-    if [ ! -w $PARENT_DESTINATION_DIRECTORY ]; then
-        sudo mkdir -p $DESTINATION_DIRECTORY
-    else
-        mkdir -p $DESTINATION_DIRECTORY
-    fi
-fi
-
-log_info "Moving Discord to destination directory..."
-if [ ! -w $DESTINATION_DIRECTORY ]; then
-    sudo mv /tmp/Discord/* $DESTINATION_DIRECTORY 2> /dev/null
-    if [[ ! $? -eq 0 ]]; then
-        log_error "Failed to move Discord to destination directory."
-        exit $?
-    fi
-else
-    mv /tmp/Discord/* $DESTINATION_DIRECTORY 2> /dev/null
-    if [[ ! $? -eq 0 ]]; then
-        log_error "Failed to move Discord to destination directory."
-        exit $?
-    fi
-fi
-log_success "Successfuly moved Discord to destination directory."
-
-log_info "Removing compressed Discord file..."
-rm -fr $DISCORD_DOWNLOAD_OUTPUT 2> /dev/null
-if [[ ! $? -eq 0 ]]; then
-    log_error "Failed to extracted compressed Discord file."
-    exit $?
-fi
-log_success "Successfuly removed compressed Discord file."
-
-log_info "Linking new binary file version..."
-
-DISCORD_BINARY_FILE_PATH=$DESTINATION_DIRECTORY/Discord
-sudo ln -s $DISCORD_BINARY_FILE_PATH $DISCORD_BINARY_LINK_FILE_PATH 2> /dev/null
-if [[ ! $? -eq 0 ]]; then
-    log_error "Failed to create Discord binary link file."
-    exit $?
-fi
-
-log_success "Successfuly linked new binary file version."
-
-log_info "Creating Discord desktop config file..."
-sudo tee $DISCORD_DESKTOP_CONFIG_FILE_PATH > /dev/null 2> /dev/null <<EOF
-[Desktop Entry]
-Name=Discord
-StartupWMClass=discord
-Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
-GenericName=Internet Messenger
-Exec=$DISCORD_BINARY_LINK_FILE_PATH
-Icon=$DESTINATION_DIRECTORY/discord.png
-Type=Application
-Categories=Network;InstantMessaging;
-Path=$BINARIES_PATH
-EOF
-
-if [[ ! $? -eq 0 ]]; then
-    log_error "Failed to create Discord desktop config file."
-    exit $?
-fi
-
-log_success "Successfuly created Discord desktop config file."
-
-log_success "Discord was successfuly updated."
-log_success "Type 'discord' or open from desktop to launch!"
+log_success "Open discord by typing \"discord\""
